<a href="https://colab.research.google.com/github/Yanina2105/MD-Lab04_FT/blob/develop/Laboratorio_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Laboratorio 4 - INTEGRACIÓN Y LIMPIEZA. TABLA DE VARIABLES Y CREACIÓN DE NUEVAS VARIABLES. TRANSFORMACIÓN DE DATOS**

Con base a datos de cáncer de mama alojados en el repositorio UCI Machine Learning Repository
(https://archive.ics.uci.edu/ml/datasets/breast+cancer+wisconsin+%28original%29) y utilizando
las librerías de Python que se indican, haga lo siguiente:

## **a. Por medio de la librería ‘Pandas’, lea la base de datos, asigne nombres para las columnas, realice una imputación para la variable ‘Bare Nuclei’ por medio de la mediana y cambie las categorías para la variable ‘Class’ de 2 o 4 por 0 o 1.**

### **Lectura de base de datos y asignación de nombres para las columnas**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data'
columnas = ['Sample_code_number', 'Clump_thickness', 'Uniformity_of_cell_size', 'Uniformity_of_cell_shape', 'Marginal_adhesion',
            'Single_epithelial_cell_size', 'Bare_nuclei', 'Bland_chromatin', 'Normal_nucleoli', 'Mitoses', 'Class']
df = pd.read_csv(url, names=columnas)
df.head()

,Sample_code_number,Clump_thickness,Uniformity_of_cell_size,Uniformity_of_cell_shape,Marginal_adhesion,Single_epithelial_cell_size,Bare_nuclei,Bland_chromatin,Normal_nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2

### **Realizar una imputación para la variable ‘Bare Nuclei’ por medio de la mediana**

In [ ]:
# Verificar el tipo de datos de Bare_nuclei
df.dtypes

Sample_code_number              int64
Clump_thickness                 int64
Uniformity_of_cell_size         int64
Uniformity_of_cell_shape        int64
Marginal_adhesion               int64
Single_epithelial_cell_size     int64
Bare_nuclei                    object
Bland_chromatin                 int64
Normal_nucleoli                 int64
Mitoses                         int64
Class                           int64
dtype: object

In [ ]:
# Convertir la columna a numérico
df['Bare_nuclei'] = pd.to_numeric(df['Bare_nuclei'], errors='coerce')

In [ ]:
df.dtypes

Sample_code_number               int64
Clump_thickness                  int64
Uniformity_of_cell_size          int64
Uniformity_of_cell_shape         int64
Marginal_adhesion                int64
Single_epithelial_cell_size      int64
Bare_nuclei                    float64
Bland_chromatin                  int64
Normal_nucleoli                  int64
Mitoses                          int64
Class                            int64
dtype: object

In [ ]:
# Imputación de la variable 'Bare_Nuclei' con la mediana
median = df['Bare_nuclei'].median()
df['Bare_nuclei'].fillna(median, inplace=True)

<ipython-input-24-5fa0866b0b9d>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Bare_nuclei'].fillna(median, inplace=True)

In [ ]:
df.isnull().sum()

Sample_code_number             0
Clump_thickness                0
Uniformity_of_cell_size        0
Uniformity_of_cell_shape       0
Marginal_adhesion              0
Single_epithelial_cell_size    0
Bare_nuclei                    0
Bland_chromatin                0
Normal_nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

### **Cambio las categorías para la variable ‘Class’ de 2 o 4 por 0 o 1.**

In [ ]:
# Cambio de categorías para la variable 'Class': 2 o 4 por 0 o 1
df['Class'] = np.where(df['Class'] == 2, 0, df['Class'])
df['Class'] = np.where(df['Class'] == 4, 1, df['Class'])

In [ ]:
df.head()

,Sample_code_number,Clump_thickness,Uniformity_of_cell_size,Uniformity_of_cell_shape,Marginal_adhesion,Single_epithelial_cell_size,Bare_nuclei,Bland_chromatin,Normal_nucleoli,Mitoses,Class,mahalanobis_distance
0,1000025,5,1,1,1,2,1.0,3,1,1,0,1.462433
1,1002945,5,4,4,5,7,10.0,3,2,1,0,3.736788
2,1015425,3,1,1,1,2,2.0,3,1,1,0,1.040197
3,1016277,6,8,8,1,3,4.0,3,7,1,0,4.098292
4,1017023,4,1,1,3,2,1.0,3,1,1,0,1.493547

## **b. Realice una detección de valores atípicos univariados por medio del método del rango intercuartílico con 3 de longitud a la derecha y 3 a la izquierda, y elimínelos. Además, realice una detección de valores atípicos multivariados por medio de las distancias de Mahalanobis y elimine aquellos valores que superen el valor de 30.**

### **Detectar de valores atípicos univariados por medio del método del rango intercuartílico con 3 de longitud a la derecha y 3 a la izquierda, y elimínarlos.**

In [ ]:
from sklearn.preprocessing import RobustScaler
from scipy.stats import chi2
from sklearn.covariance import MinCovDet

In [ ]:
# Detección de valores atípicos univariados (método del rango intercuartílico)
Q1 = df['Class'].quantile(0.25)
Q3 = df['Class'].quantile(0.75)
IQR = Q3 - Q1
limite_inferior = Q1 - 3 * IQR
print('Valor atipicos del limite inferior',limite_inferior)
limite_superior = Q3 + 3 * IQR
print('Valor atipicos del limite superior',limite_superior)

Valor atipicos del limite inferior -3.0
Valor atipicos del limite superior 4.0

In [ ]:
df['Class']

0      0
1      0
2      0
3      0
4      0
      ..
694    0
695    0
696    1
697    1
698    1
Name: Class, Length: 699, dtype: int64

In [ ]:
# Eliminación de valores atípicos univariados
df_clean = df[(df['Class'] >= limite_inferior) & (df['Class'] <= limite_superior)]

In [ ]:
df['Class']

0      0
1      0
2      0
3      0
4      0
      ..
694    0
695    0
696    1
697    1
698    1
Name: Class, Length: 699, dtype: int64

### **Detección de valores atípicos multivariados por medio de las distancias de Mahalanobis y elimine aquellos valores que superen el valor de 30.**

In [ ]:
from scipy.spatial.distance import mahalanobis

In [ ]:
# Seleccionamos las columnas numéricas (ajusta según tu dataset)
cols = ['Clump_thickness', 'Uniformity_of_cell_size']

X = df[cols]

In [ ]:
# Media y matriz de covarianza inversa
mean = X.mean().values
cov = np.cov(X.values.T)  # Usamos X.T porque debe ser una matriz de 2x2
inv_cov = np.linalg.inv(cov)

# Calcular la distancia de Mahalanobis para cada fila
dist_maha = X.apply(lambda row: mahalanobis(row.values, mean, inv_cov), axis=1)

# Agregar la distancia como una nueva columna
df['mahalanobis_distance'] = dist_maha

In [ ]:
df['mahalanobis_distance']

0      1.109203
1      0.285356
2      0.702845
3      1.707273
4      0.803878
         ...
694    0.702845
695    0.879572
696    2.777139
697    2.216491
698    2.216491
Name: mahalanobis_distance, Length: 699, dtype: float64

In [ ]:
# Filtrar los datos que tienen distancia menor o igual a 30
df_clean_maha = df[df['mahalanobis_distance'] <= 30].copy()

## **c. Realice un cálculo de los principales estadísticos descriptivos para las variables predictoras y cree dos conjuntos de datos: uno en donde se aplique la transformación Z-score y otro en donde se aplique la normalización mín-máx, sobre todas las variables predictoras.**

### **Realice un cálculo de los principales estadísticos descriptivos para las variables predictoras: Transformación Z-score**

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
# Calcular los estadísticos descriptivos y convertirlo en DataFrame
df_description = df.describe()

# Ver los primeros registros
df_description.head()

,Sample_code_number,Clump_thickness,Uniformity_of_cell_size,Uniformity_of_cell_shape,Marginal_adhesion,Single_epithelial_cell_size,Bare_nuclei,Bland_chromatin,Normal_nucleoli,Mitoses,Class,mahalanobis_distance
count,6.990000e+02,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000
mean,1.071704e+06,4.417740,3.134478,3.207439,2.806867,3.216023,3.486409,3.437768,2.866953,1.589413,0.344778,1.262694
std,6.170957e+05,2.815741,3.051459,2.971913,2.855379,2.214300,3.621929,2.438364,3.053634,1.715078,0.475636,0.635075
min,6.163400e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.163004
25%,8.706885e+05,2.000000,1.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,0.000000,0.803878

In [ ]:
# Seleccionar las columnas predictoras
X = df.drop(columns=['Class'])  # asumiendo que 'Class' es la variable objetivo

In [ ]:
# Crear el objeto StandardScaler
scaler = StandardScaler()

In [ ]:
# Aplicar la transformación Z-score
X_zscore = scaler.fit_transform(X)

In [ ]:
# Convertir a DataFrame con las columnas originales
df_zscore = pd.DataFrame(X_zscore, columns=X.columns)

# Ver el resultado
print(df_zscore.describe())

       Sample_code_number  Clump_thickness  Uniformity_of_cell_size  \
count        6.990000e+02     6.990000e+02             6.990000e+02
mean        -9.148619e-17    -5.082566e-17            -9.148619e-17
std          1.000716e+00     1.000716e+00             1.000716e+00
min         -1.637985e+00    -1.214667e+00            -6.999951e-01
25%         -3.259779e-01    -8.592662e-01            -6.999951e-01
50%          1.621750e-01    -1.484649e-01            -6.999951e-01
75%          2.701578e-01     5.623364e-01             6.117919e-01
max          2.008038e+01     1.983939e+00             2.251526e+00

       Uniformity_of_cell_shape  Marginal_adhesion  \
count              6.990000e+02       6.990000e+02
mean              -3.049540e-17       5.082566e-17
std                1.000716e+00       1.000716e+00
min               -7.432990e-01      -6.332472e-01
25%               -7.432990e-01      -6.332472e-01
50%               -7.432990e-01      -6.332472e-01
75%                6.035993e-01       4.181537e-01
max                2.287222e+00       2.520955e+00

       Single_epithelial_cell_size   Bare_nuclei  Bland_chromatin  \
count                 6.990000e+02  6.990000e+02     6.990000e+02
mean                  5.082566e-17 -8.132106e-17     3.049540e-17
std                   1.000716e+00  1.000716e+00     1.000716e+00
min                  -1.001495e+00 -6.869792e-01    -1.000471e+00
25%                  -5.495614e-01 -6.869792e-01    -5.900668e-01
50%                  -5.495614e-01 -6.869792e-01    -1.796621e-01
75%                   3.543054e-01  4.181956e-01     6.411472e-01
max                   3.065906e+00  1.799664e+00     2.693171e+00

       Normal_nucleoli       Mitoses  mahalanobis_distance
count     6.990000e+02  6.990000e+02          6.990000e+02
mean     -1.321467e-16 -8.132106e-17          1.219816e-16
std       1.000716e+00  1.000716e+00          1.000716e+00
min      -6.118250e-01 -3.439118e-01         -1.732831e+00
25%      -6.118250e-01 -3.439118e-01         -7.229765e-01
50%      -6.118250e-01 -3.439118e-01         -2.359908e-01
75%       3.713145e-01 -3.439118e-01          3.720044e-01
max       2.337594e+00  4.907421e+00          3.377659e+00

### **Realice un cálculo de los principales estadísticos descriptivos para las variables predictoras: Normalización mín-máx**

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
# Crear el objeto MinMaxScaler
min_max_scaler = MinMaxScaler()

In [ ]:
# Aplicar la transformación Min-Max
X_minmax = min_max_scaler.fit_transform(X)

In [ ]:
# Convertir a DataFrame con las columnas originales
df_minmax = pd.DataFrame(X_minmax, columns=X.columns)

# Ver el resultado
print(df_minmax.describe())

       Sample_code_number  Clump_thickness  Uniformity_of_cell_size  \
count          699.000000       699.000000               699.000000
mean             0.075419         0.379749                 0.237164
std              0.046077         0.312860                 0.339051
min              0.000000         0.000000                 0.000000
25%              0.060410         0.111111                 0.000000
50%              0.082887         0.333333                 0.000000
75%              0.087858         0.555556                 0.444444
max              1.000000         1.000000                 1.000000

       Uniformity_of_cell_shape  Marginal_adhesion  \
count                699.000000         699.000000
mean                   0.245271           0.200763
std                    0.330213           0.317264
min                    0.000000           0.000000
25%                    0.000000           0.000000
50%                    0.000000           0.000000
75%                    0.444444           0.333333
max                    1.000000           1.000000

       Single_epithelial_cell_size  Bare_nuclei  Bland_chromatin  \
count                   699.000000   699.000000       699.000000
mean                      0.246225     0.276268         0.270863
std                       0.246033     0.402437         0.270929
min                       0.000000     0.000000         0.000000
25%                       0.111111     0.000000         0.111111
50%                       0.111111     0.000000         0.222222
75%                       0.333333     0.444444         0.444444
max                       1.000000     1.000000         1.000000

       Normal_nucleoli     Mitoses  mahalanobis_distance
count       699.000000  699.000000            699.000000
mean          0.207439    0.065490              0.339073
std           0.339293    0.190564              0.195816
min           0.000000    0.000000              0.000000
25%           0.000000    0.000000              0.197604
50%           0.000000    0.000000              0.292896
75%           0.333333    0.000000              0.411866
max           1.000000    1.000000              1.000000